version: "3.3"

services:
  server:
    ports:
      - 3000:3000
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server

  proxy_server:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-server
    depends_on:
      - server
