version: "3.3"

services:
  proxy_server:
    image: nginx:1.20.1
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-server
    depends_on:
      - node-server

  node-server:
    ports:
      - 3000:3000
    build:
      context: ./node-server
      dockerfile: Dockerfile
    container_name: node-server
