version: "3.3"

services:
  app:
    ports:
      - 3000:3000
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: app

  proxy_server:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    container_name: reverse-proxy-server
    depends_on:
      - app
