version: "3.3"

services:
  app:
    ports:
      - 3000:3000
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: app-2

  proxy_server:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-server-2
    depends_on:
      - app
